"""add default value for date of death

Revision ID: 5bfa191fd64f
Revises: 3af2dfe0f278
Create Date: 2024-03-25 18:44:17.370894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfa191fd64f'
down_revision: Union[str, None] = '3af2dfe0f278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
